# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check and build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npm run check:prettier
      - run: npm run check:ts
      - run: npm run check:astro
      - name: Cache
        uses: actions/cache@v3.2.3
        id: cache
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            node_modules
            dist/assets
          # An explicit key for restoring and saving the cache
          key: hashFiles('**/package-lock.json')
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Check cache
        if: steps.check.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build
